import oxAtlas from './ox-atlas/manifest.js'
import oxMasque from './ox-masque/manifest.js'
import oxHours from './ox-hours/manifest.js'
import oxVesper from './ox-vesper/manifest.js'
import oxVita from './ox-vita/manifest.js'
import oxMythos from './ox-mythos/manifest.js'
import oxYoke from './ox-yoke/manifest.js'
import oxEpoch from './ox-epoch/manifest.js'
import oxLexicon from './ox-lexicon/manifest.js'
import oxMeridian from './ox-meridian/manifest.js'
import oxSpan from './ox-span/manifest.js'
import oxTale from './ox-tale/manifest.js'
import oxApparatus from './ox-apparatus/manifest.js'

export const SETS = [oxAtlas, oxMasque, oxHours, oxVesper, oxVita, oxMythos, oxYoke, oxEpoch, oxLexicon, oxMeridian, oxSpan, oxTale, oxApparatus]
